# Generated by Django 3.1.2 on 2020-10-27 17:19

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('company', models.CharField(blank=True, max_length=50)),
                ('dept', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('tel_number', models.CharField(blank=True, max_length=255)),
                ('fax_number', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('birthday', models.DateField(null=True)),
                ('bio', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('M', '남자'), ('F', '여자'), ('C', 'Custom')], max_length=30)),
                ('like', models.CharField(blank=True, max_length=30)),
                ('dislike', models.CharField(blank=True, max_length=30)),
                ('group', models.ManyToManyField(to='contactlist.ContactGroup')),
                ('tag', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
